// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqiadoqsbaczlkptdeme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xaWFkb3FzYmFjemxrcHRkZW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTk3OTUsImV4cCI6MjA3NDQzNTc5NX0.1heN3vcK99KqV6i7Zx_KoNFC990VdxvSWOnjJRrKpHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});